use_frameworks!

platform :ios, '9.0'

target 'JPCrop_Example' do
  pod 'JPCrop', :path => '../'
  pod 'pop'
  
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      end
    end
  end
end
